{{- if .Values.configMaps.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend-spa.fullname" . }}-config
  labels:
    {{- include "frontend-spa.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMaps.data | nindent 2 }}
{{- end }}