replicaCount: 1

image:
  repository: frontend-spa
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

extraEnvVars:
  - name: NODE_ENV
    value: production
  - name: API_URL
    value: https://api.example.com

cdn:
  provider: cloudflare
  enabled: true
  zoneId: ""
  distributionId: ""
  pathPattern: "/*"

configMaps:
  enabled: false
  data: {}

nodeSelector: {}
tolerations: []
affinity: {}
